version: "3"
networks:
  webappnetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.28.1.0/24"
volumes:
  mongo-data:
    driver: local
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      webappnetwork:
        ipv4_address: 172.28.1.2
  app:
    build: .
    depends_on:
    - mongo
    environment:
      - MONGO_PORT=27017
      - MONGO_DB=pokecards
      - MONGO_HOSTNAME=172.28.1.2
    ports:
    - "8080:8080"
    networks:
      webappnetwork:
        ipv4_address: 172.28.1.3